#name: lab2pam
#description: "A new Flutter project."
#publish_to: 'none'

#version: 1.0.0+1
#
#environment:
#  sdk: ^3.5.2

#dependencies:
#  flutter:
#    sdk: flutter
#  cupertino_icons: ^1.0.8
#  smooth_page_indicator: ^1.0.0+2
#  get: ^4.6.5
#  # Add references to the local packages
#  domain:
#    path: domain
#  data:
#    path: data
#  presentation:
#    path: presentation
#  di:
#    path: di
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^4.0.0

#flutter:
#  uses-material-design: true

#  assets:
#    - assets/images/clinic.png
#    - assets/images/doctor.png
#    - assets/images/golden.png
#    - assets/images/republican.jpg
#    - assets/images/doctor1.png
#    - assets/images/doctor2.png
#    - assets/images/doctor3.png
#    - assets/images/doctor4.png
#    - assets/images/doctor5.png
#    - assets/images/dental.png
#    - assets/images/cardio.png
#    - assets/images/pulmo.png
#    - assets/images/general.png
#    - assets/images/neurology.png
#    - assets/images/gastro.png
#    - assets/images/lab.png
#    - assets/images/vaccination.png
#    - assets/v1.json
