name: presentation
description: "Presentation layer for UI and widgets."
version: 1.0.0

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain
  di:
    path: ../di
  # State management and UI libraries
  get: ^4.6.5
  smooth_page_indicator: ^1.0.0
  # Add any other dependencies as needed

flutter:
  assets:
    - ../assets/v1.json

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
